# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 974670c3306e975ead66878f3f70ca98623592949d1ee2099abc1af90128bc2fef1e0ec55f2af8c1982813d4436b5753f252178520c1bd47a2c57f8664eb63c2

test:
  secret_key_base: c40e3d98b32bc321ac1f68080e11222ce977e17eda8b2f28c24dfde58e9661fb51d745e9de9a5c7fc8ee7e3a057184731072047491fb6cfc4f1dc2ae59ea286a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
